name: chatgpt
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dart_openai: ^4.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  hive_flutter: ^1.1.0
  flutter_spinkit: ^5.2.0
  google_fonts: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/data/dataresources/local/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "lib/data/dataresources/local/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "lib/data/dataresources/local/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "lib/data/dataresources/local/icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/data/dataresources/local/
